services:
  nef-exposure:
    build:
      context: .
    container_name: nef-exposure
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./app:/app
    restart: no
    command: ["--host", "${HOST}", "--port", "${PORT}"]
  test-server:
    image: python:3.12.10-slim
    container_name: test_server
    ports:
      - "8001:8001"
    volumes:
      - ./test_server.py:/test_server.py
    restart: no
    command: ["/bin/sh", "-c", "python test_server.py"]
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: no
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5
